import json
from datetime import datetime, timedelta
from typing import Any, Literal

from pydantic import AliasChoices, Field, field_validator, model_validator
from pydantic import BaseModel as BaseSchema

from kraken.constants import LATENCY_TOLERANCE
from kraken.utilities import utc_now

ORDER_TYPE = Literal[
    "market",
    "limit",
    "iceberg",
    "stop-loss",
    "take-profit",
    "stop-loss-limit",
    "take-profit-limit",
    "trailing-stop",
    "trailing-stop-limit",
    "settle-position",
]
ORDER_DIRECTION = Literal["buy", "sell"]
ORDER_FLAG_SET = set(["post", "fcib", "fciq", "viqc"])
TRIGGER_TYPE = Literal["index", "last"]
STP_TYPE = Literal["cancel-newest", "cancel-oldest", "cancel-both"]
TIME_IN_FORCE = Literal["GTC", "IOC", "GTD", "PO"]


class ResponseErrorSchema(BaseSchema):
    """Error response from Kraken API.

    Contains error messages when order placement fails.
    """

    error: list[str] = Field(
        ...,
        description="List of error messages from the API.",
    )


class AddOrderRequest(BaseSchema):
    """Schema for Kraken AddOrder API request.

    This schema validates and prepares order data for submission to Kraken's
    AddOrder API endpoint. It is safe for concurrent async usage when properly
    serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - The 'deadline' parameter is NOT auto-generated during instantiation
          to prevent stale timestamps in async scenarios. The REST client
          will generate it at request time if None.
        - Use to_api_dict() to serialize for API submission (handles field
          aliasing like 'only_validate' -> 'validate').

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        Time-sensitive fields (nonce, deadline) are handled by the REST client
        at the last possible moment before request signing.

    Usage Examples:
        Basic market order:
        >>> order = AddOrderRequest(
        ...     ordertype="market",
        ...     type="buy",
        ...     volume=1.5,
        ...     pair="XBTUSD"
        ... )
        >>> data = order.to_api_dict()
        >>> response = client.request("AddOrder", data=data)

        Limit order with custom deadline:
        >>> from datetime import datetime, timedelta, timezone
        >>> deadline = (datetime.now(timezone.utc) + timedelta(seconds=10)).isoformat()
        >>> order = AddOrderRequest(
        ...     ordertype="limit",
        ...     type="sell",
        ...     volume=0.5,
        ...     pair="ETHUSD",
        ...     price="2000.50",
        ...     deadline=deadline
        ... )

        Validation only (no execution):
        >>> order = AddOrderRequest(
        ...     ordertype="limit",
        ...     type="buy",
        ...     volume=1,
        ...     pair="XBTUSD",
        ...     price="50000",
        ...     only_validate=True  # Test order validity without placing
        ... )

        Async usage (deadline computed at request time):
        >>> order = AddOrderRequest(
        ...     ordertype="market",
        ...     type="buy",
        ...     volume=1,
        ...     pair="XBTUSD"
        ... )
        >>> # Deadline remains None during queueing/delays
        >>> await asyncio.sleep(5)
        >>> # REST client will compute deadline at signing time
        >>> response = await client.arequest("AddOrder", data=order.to_api_dict())
    """

    userref: int | None = Field(
        default=None,
        description="This is an optional non-unique, numeric identifier for user metadata tracking. This field is mutually exclusive with `cl_ord_id` parameter.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Adds an alphanumeric client order identifier which uniquely identifies an open order for each client (long/short UUID or 18-ascii char). This field is mutually exclusive with `userref` parameter.",
    )
    ordertype: ORDER_TYPE = Field(..., description="The execution model of the order.")
    type: ORDER_DIRECTION = Field(..., description="Order direction (buy/sell).")
    volume: str | float | int = Field(
        ...,
        description="Order quantity in terms of the base asset; can be specified as 0 for closing margin orders to automatically fill the requisite quantity.",
    )
    displayvol: str | float | int | None = Field(
        default=None,
        description="For 'iceberg' orders only, it defines the quantity to show in the book while the rest of order quantity remains hidden. Minimum value is 1/15 of volume.",
    )
    pair: str = Field(..., description="Asset pair `id` or `altname`.")
    asset_class: str | None = Field(
        None, description="Required to be set as 'tokenized_asset' for non-crypto pairs (xstocks)."
    )
    price: str | None = Field(
        default=None,
        description="Limit price for 'limit' and 'iceberg' orders; trigger price for 'stop-loss', 'stop-loss-limit', 'take-profit', 'take-profit-limit', 'trailing-stop' and 'trailing-stop-limit' orders.",
    )
    price2: str | None = Field(
        default=None,
        description="Limit price for 'stop-loss-limit', 'take-profit-limit' and 'trailing-stop-limit' orders.",
    )
    trigger: TRIGGER_TYPE | None = Field(
        default=None,
        description="Price signal used to trigger 'stop-loss', 'stop-loss-limit', 'take-profit', 'take-profit-limit', 'trailing-stop' and 'trailing-stop-limit' orders.",
    )
    leverage: str | int | None = Field(None, description="Amount of desired leverage.")
    reduce_only: bool = Field(
        default=False,
        description="If `True`, order will only reduce a currently open position, not increase it or open a new position.",
    )
    stptype: STP_TYPE | None = Field(
        default=None,
        description="Self Trade Prevention (STP) behavior. If None, uses Kraken's default. Options: 'cancel-newest', 'cancel-oldest', 'cancel-both'.",
    )
    oflags: str | list[str] | set[str] | None = Field(
        default=None,
        description="Comma delimited list of order flags: 'post', 'fcib', 'fciq', 'viqc'.",
    )
    timeinforce: TIME_IN_FORCE | None = Field(
        default="GTC",
        description="Time-in-force of the order to specify how long it should remain in the order book before being cancelled.",
    )
    starttm: str | None = Field(
        default="0",
        description="Scheduled start time, can be specified as an absolute timestamp or as a number of seconds in the future.",
    )
    expiretm: str | None = Field(
        default="0",
        description="Expiry time on GTD orders can be set up to one month in future, it is specified as an absolute timestamp or as a number of seconds from now.",
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the new order request, in presence of latency or order queueing.",
    )
    only_validate: bool = Field(
        default=False,
        description="If True, validates order inputs without placing the order. Set to True for testing order parameters without execution.",
        validation_alias=AliasChoices("only_validate", "validate"),  # Accept both names
        serialization_alias="validate",  # Send as 'validate' to API
    )
    close_ordertype: ORDER_TYPE | None = Field(
        default=None,
        description="Conditional close order type for positions. Used with 'close_price' and optionally 'close_price2' to create an OCO (One-Cancels-Other) order.",
    )
    close_price: str | None = Field(
        default=None,
        description="Conditional close order price. Required when 'close_ordertype' is specified.",
    )
    close_price2: str | None = Field(
        default=None,
        description="Conditional close order secondary price for stop-loss-limit or take-profit-limit orders.",
    )

    @field_validator("ordertype", mode="before")
    @classmethod
    def lowercase_order(cls, value: str) -> str:
        return value.lower().strip()

    @field_validator("volume", mode="before")
    @classmethod
    def string_volume(cls, value: str | float | int) -> str:
        return str(value)

    @field_validator("displayvol", mode="before")
    @classmethod
    def floor_display_volume(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_volume = float(info.data.get("volume"))
        floor_volume = order_volume / 15.0
        if float(value) > order_volume:
            return str(order_volume)
        elif float(value) < floor_volume:
            return str(floor_volume)
        else:
            return str(value)

    @field_validator("leverage", mode="before")
    @classmethod
    def string_leverage(cls, value: str | float | None) -> str | None:
        if value is None:
            return None
        return str(value)

    @field_validator("oflags", mode="before")
    @classmethod
    def concat_order_flags(cls, value: str | list[str] | set[str] | None) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            splits = value.split(",")
            if len(splits) > 1:
                value = set(splits)
            else:
                value = {value}
        elif isinstance(value, list):
            value = set(value)
        value = ORDER_FLAG_SET.intersection(value)
        return ",".join(value) if len(value) > 0 else None

    @field_validator("timeinforce", mode="before")
    @classmethod
    def capitalize_time_in_force(cls, value: str) -> str:
        return value.upper().strip()

    @field_validator("deadline", mode="after")
    @classmethod
    def validate_deadline(cls, value: str | None) -> str | None:
        """Validate deadline format and timezone information.

        Note: Deadline is NOT auto-generated here to prevent race conditions.
        The REST client will generate the deadline at request signing time
        if None is provided, ensuring accurate timing for async operations.
        """
        if value is None:
            return None

        deadline = datetime.fromisoformat(value)
        if deadline.tzinfo is None:
            raise ValueError(
                "Deadline must include timezone information (RFC3339 format). "
                "Example: '2025-01-15T12:00:00+00:00' or use 'Z' for UTC."
            )

        # Validate deadline is bounded between 2-60 seconds from now
        now = utc_now()
        min_t, max_t = now + timedelta(seconds=2), now + timedelta(seconds=60)
        deadline_utc = deadline.astimezone(now.tzinfo)

        if deadline_utc < min_t:
            deadline_utc = min_t
        elif deadline_utc > max_t:
            deadline_utc = max_t

        return deadline_utc.isoformat()

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "AddOrderRequest":
        """Validate field dependencies for different order types."""
        if (
            self.ordertype in ["iceberg", "limit", "stop-loss", "take-profit", "trailing-stop"]
            and self.price is None
        ):
            raise ValueError(f"{self.ordertype} orders require 'price' field")
        if self.ordertype in ["stop-loss-limit", "take-profit-limit", "trailing-stop-limit"]:
            if self.price is None or self.price2 is None:
                raise ValueError(
                    f"{self.ordertype} orders require both 'price' and 'price2' fields"
                )
        if self.close_ordertype is not None and self.close_price is None:
            raise ValueError("Conditional close orders require 'close_price' field")
        if self.close_ordertype in ["stop-loss-limit", "take-profit-limit"]:
            if self.close_price2 is None:
                raise ValueError(
                    f"Conditional close {self.close_ordertype} orders require 'close_price2' field"
                )
        if self.timeinforce == "GTD" and (self.expiretm is None or self.expiretm == "0"):
            raise ValueError("GTD (Good-Til-Date) orders require 'expiretm' field")
        if self.userref is not None and self.cl_ord_id is not None:
            raise ValueError("'userref' and 'cl_ord_id' are mutually exclusive")
        return self

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize order to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing orders to the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API AddOrder endpoint

        Example:
            >>> order = AddOrderRequest(
            ...     ordertype="limit",
            ...     type="buy",
            ...     volume=1.5,
            ...     pair="XBTUSD",
            ...     price="50000"
            ... )
            >>> data = order.to_api_dict()
            >>> # Pass to REST client
            >>> response = client.request("AddOrder", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )

    @staticmethod
    def compute_deadline(latency_tolerance: int = LATENCY_TOLERANCE) -> str:
        """Compute a deadline timestamp for order submission.

        This is a utility method that should be called by the REST client
        at request signing time, not during order instantiation.

        Args:
            latency_tolerance: Seconds to add to current time for deadline

        Returns:
            RFC3339 formatted deadline string
        """
        now = utc_now()
        deadline = now + timedelta(seconds=latency_tolerance)
        min_t, max_t = now + timedelta(seconds=2), now + timedelta(seconds=60)
        if deadline < min_t:
            deadline = min_t
        elif deadline > max_t:
            deadline = max_t
        return deadline.isoformat()


class AddOrderSuccess(BaseSchema):
    """Successful AddOrder response from Kraken API.

    Contains order details and transaction IDs when an order is successfully
    placed or validated.
    """

    txid: list[str] = Field(
        ...,
        description="18-character transaction IDs for the order(s) placed.",
    )
    descr: dict = Field(
        ...,
        description="Order description containing 'order' and optionally 'close' fields.",
    )

    @property
    def order_description(self) -> str:
        """Get the order description string."""
        return self.descr.get("order", "")

    @property
    def close_description(self) -> str | None:
        """Get the conditional close order description, if any."""
        return self.descr.get("close")


class AddOrderResponse(BaseSchema):
    """Combined response wrapper for AddOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: AddOrderSuccess | None = Field(
        default=None,
        description="Success response data, present when order placement succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when order placement fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "AddOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AddOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = AddOrderSuccess(
            txid=result["txid"],
            descr=result["descr"],
        )
        return cls(success=success_data)


class AmendOrderRequest(BaseSchema):
    """Schema for Kraken AmendOrder API request.

    This schema validates and prepares order amendment data for submission to
    Kraken's AmendOrder API endpoint. It is safe for concurrent async usage when
    properly serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - The 'deadline' parameter is NOT auto-generated during instantiation
          to prevent stale timestamps in async scenarios. The REST client
          will generate it at request time if None.
        - Either 'txid' or 'cl_ord_id' must be provided to identify the order.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        Time-sensitive fields (nonce, deadline) are handled by the REST client
        at the last possible moment before request signing.

    Usage Examples:
        Amend order quantity by txid:
        >>> amend = AmendOrderRequest(
        ...     txid="OUF4EM-FRGI2-MQMWZD",
        ...     order_qty=2.5
        ... )
        >>> data = amend.to_api_dict()
        >>> response = client.request("AmendOrder", data=data)

        Amend limit price by client order ID:
        >>> amend = AmendOrderRequest(
        ...     cl_ord_id="my-order-123",
        ...     limit_price="51000.50"
        ... )
        >>> response = client.request("AmendOrder", data=amend.to_api_dict())

        Amend with relative pricing:
        >>> amend = AmendOrderRequest(
        ...     txid="ABC-123",
        ...     limit_price="+100",  # Add 100 to current reference price
        ...     trigger_price="-50%"  # Subtract 50% from reference price
        ... )

        Amend iceberg order display quantity:
        >>> amend = AmendOrderRequest(
        ...     txid="OUF4EM-FRGI2-MQMWZD",
        ...     display_qty=5.0,
        ...     pair="XBTUSD"
        ... )

        Async usage (deadline computed at request time):
        >>> amend = AmendOrderRequest(
        ...     txid="OUF4EM-FRGI2-MQMWZD",
        ...     order_qty=1.5
        ... )
        >>> # Deadline remains None during queueing/delays
        >>> await asyncio.sleep(5)
        >>> # REST client will compute deadline at signing time
        >>> response = await client.arequest("AmendOrder", data=amend.to_api_dict())
    """

    txid: str | None = Field(
        default=None,
        description="The Kraken identifier for the order to be amended. Either txid or cl_ord_id is required.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="The client identifier for the order to be amended. Either txid or cl_ord_id is required.",
    )
    order_qty: str | float | int | None = Field(
        default=None,
        description="The new order quantity in terms of the base asset.",
    )
    display_qty: str | float | int | None = Field(
        default=None,
        description="For iceberg orders only, it defines the new quantity to show in the book while the rest of order quantity remains hidden. Minimum value is 1/15 of remaining order quantity.",
    )
    limit_price: str | None = Field(
        default=None,
        description="The new limit price restriction on the order (for order types that support limit price only). Supports relative pricing: +/- prefix to add/subtract from reference price, % suffix for percentage adjustments.",
    )
    trigger_price: str | None = Field(
        default=None,
        description="The new trigger price to activate the order (for triggered order types only). Supports relative pricing: +/- prefix to add/subtract from reference price, % suffix for percentage adjustments.",
    )
    pair: str | None = Field(
        default=None,
        description="The pair is required on amends for non-crypto pairs (xstocks). Provide the pair symbol for tokenized assets.",
    )
    post_only: bool = Field(
        default=False,
        description="An optional flag for limit_price amends. If true, the limit price change will be rejected if the order cannot be posted passively in the book.",
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the amend request, in presence of latency or order queueing.",
    )

    @field_validator("order_qty", mode="before")
    @classmethod
    def string_order_qty(cls, value: str | float | int | None) -> str | None:
        if value is None:
            return None
        return str(value)

    @field_validator("display_qty", mode="before")
    @classmethod
    def floor_display_qty(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_qty = info.data.get("order_qty")  # If order_qty is provided, use it for floor calc
        if order_qty is not None:
            order_volume = float(order_qty)
            floor_volume = order_volume / 15.0
            if float(value) > order_volume:
                return str(order_volume)
            elif float(value) < floor_volume:
                return str(floor_volume)
        return str(value)

    @field_validator("deadline", mode="after")
    @classmethod
    def validate_deadline(cls, value: str | None) -> str | None:
        """Validate deadline format and timezone information.

        Note: Deadline is NOT auto-generated here to prevent race conditions.
        The REST client will generate the deadline at request signing time
        if None is provided, ensuring accurate timing for async operations.
        """
        if value is None:
            return None
        deadline = datetime.fromisoformat(value)
        if deadline.tzinfo is None:
            raise ValueError(
                "Deadline must include timezone information (RFC3339 format). "
                "Example: '2025-01-15T12:00:00+00:00' or use 'Z' for UTC."
            )
        now = utc_now()
        min_t, max_t = now + timedelta(seconds=2), now + timedelta(seconds=60)
        deadline_utc = deadline.astimezone(now.tzinfo)
        if deadline_utc < min_t:
            deadline_utc = min_t
        elif deadline_utc > max_t:
            deadline_utc = max_t
        return deadline_utc.isoformat()

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "AmendOrderRequest":
        """Validate field dependencies for amend requests."""
        if self.txid is None and self.cl_ord_id is None:
            raise ValueError("Either 'txid' or 'cl_ord_id' must be provided")
        if self.txid is not None and self.cl_ord_id is not None:
            raise ValueError("'txid' and 'cl_ord_id' are mutually exclusive")
        return self

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize amend request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing amend requests to
        the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API AmendOrder endpoint

        Example:
            >>> amend = AmendOrderRequest(
            ...     txid="OUF4EM-FRGI2-MQMWZD",
            ...     order_qty=2.5,
            ...     limit_price="51000"
            ... )
            >>> data = amend.to_api_dict()
            >>> # Pass to REST client
            >>> response = client.request("AmendOrder", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )

    @staticmethod
    def compute_deadline(latency_tolerance: int = LATENCY_TOLERANCE) -> str:
        """Compute a deadline timestamp for amend request submission.

        This is a utility method that should be called by the REST client
        at request signing time, not during amend instantiation.

        Args:
            latency_tolerance: Seconds to add to current time for deadline

        Returns:
            RFC3339 formatted deadline string
        """
        now = utc_now()
        deadline = now + timedelta(seconds=latency_tolerance)
        min_t, max_t = now + timedelta(seconds=2), now + timedelta(seconds=60)
        if deadline < min_t:
            deadline = min_t
        elif deadline > max_t:
            deadline = max_t
        return deadline.isoformat()


class AmendOrderSuccess(BaseSchema):
    """Successful AmendOrder response from Kraken API.

    Contains the unique amend transaction identifier when an order amendment
    is successfully processed.
    """

    amend_id: str = Field(
        ...,
        description="The unique Kraken identifier generated for this amend transaction.",
    )


class AmendOrderResponse(BaseSchema):
    """Combined response wrapper for AmendOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: AmendOrderSuccess | None = Field(
        default=None,
        description="Success response data, present when order amendment succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when order amendment fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "AmendOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AmendOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = AmendOrderSuccess(amend_id=result["amend_id"])
        return cls(success=success_data)


class CancelOrderRequest(BaseSchema):
    """Schema for Kraken CancelOrder API request.

    This schema validates and prepares order cancellation data for submission to
    Kraken's CancelOrder API endpoint. It is safe for concurrent async usage when
    properly serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - Either 'txid' or 'cl_ord_id' must be provided to identify the order(s).
        - The 'txid' field accepts either a string (single order ID), integer
          (user reference), or string representation of an integer.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Cancel by transaction ID:
        >>> cancel = CancelOrderRequest(txid="OUF4EM-FRGI2-MQMWZD")
        >>> data = cancel.to_api_dict()
        >>> response = client.request("CancelOrder", data=data)

        Cancel by user reference (integer):
        >>> cancel = CancelOrderRequest(txid=12345)
        >>> response = client.request("CancelOrder", data=cancel.to_api_dict())

        Cancel by client order ID:
        >>> cancel = CancelOrderRequest(cl_ord_id="my-order-123")
        >>> response = client.request("CancelOrder", data=cancel.to_api_dict())

        Async usage:
        >>> cancel = CancelOrderRequest(txid="OUF4EM-FRGI2-MQMWZD")
        >>> await asyncio.sleep(5)
        >>> # REST client will compute nonce at signing time
        >>> response = await client.arequest("CancelOrder", data=cancel.to_api_dict())
    """

    txid: str | int | None = Field(
        default=None,
        description="Kraken order identifier (txid) or user reference (userref). Can be a string (txid), integer (userref), or string representation of either.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="An alphanumeric client order identifier which uniquely identifies an open order for each client.",
    )

    @field_validator("txid", mode="before")
    @classmethod
    def normalize_txid(cls, value: str | int | None) -> str | int | None:
        """Normalize txid - convert string integers to int, keep string txids as strings."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, str):
            try:
                return int(value)
            except ValueError:
                return value.strip()
        return value

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "CancelOrderRequest":
        """Validate field dependencies for cancel requests."""
        if self.txid is None and self.cl_ord_id is None:
            raise ValueError("Either 'txid' or 'cl_ord_id' must be provided")
        if self.txid is not None and self.cl_ord_id is not None:
            raise ValueError("'txid' and 'cl_ord_id' are mutually exclusive")
        return self

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize cancel request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing cancel requests to
        the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API CancelOrder endpoint

        Example:
            >>> cancel = CancelOrderRequest(txid="OUF4EM-FRGI2-MQMWZD")
            >>> data = cancel.to_api_dict()
            >>> # Pass to REST client
            >>> response = client.request("CancelOrder", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )


class CancelOrderSuccess(BaseSchema):
    """Successful CancelOrder response from Kraken API.

    Contains information about the number of orders cancelled and whether
    cancellation is pending.
    """

    count: int = Field(
        ...,
        description="Number of orders cancelled.",
    )
    pending: bool | None = Field(
        default=None,
        description="If true, orders are pending cancellation.",
    )


class CancelOrderResponse(BaseSchema):
    """Combined response wrapper for CancelOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: CancelOrderSuccess | None = Field(
        default=None,
        description="Success response data, present when order cancellation succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when order cancellation fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = CancelOrderSuccess(
            count=result["count"],
            pending=result.get("pending"),
        )
        return cls(success=success_data)


class CancelAllRequest(BaseSchema):
    """Schema for Kraken CancelAll API request.

    This schema validates and prepares data for submission to Kraken's
    CancelAll API endpoint, which cancels all open orders. It is safe for
    concurrent async usage when properly serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - This endpoint has no additional parameters beyond nonce.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Cancel all open orders:
        >>> cancel_all = CancelAllRequest()
        >>> data = cancel_all.to_api_dict()
        >>> response = client.request("CancelAll", data=data)

        Async usage:
        >>> cancel_all = CancelAllRequest()
        >>> response = await client.arequest("CancelAll", data=cancel_all.to_api_dict())
    """

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize cancel all request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing cancel all requests
        to the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API CancelAll endpoint

        Example:
            >>> cancel_all = CancelAllRequest()
            >>> data = cancel_all.to_api_dict()
            >>> # Pass to REST client
            >>> response = client.request("CancelAll", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )


class CancelAllSuccess(BaseSchema):
    """Successful CancelAll response from Kraken API.

    Contains information about the number of orders cancelled and whether
    cancellation is pending.
    """

    count: int = Field(
        ...,
        description="Number of orders cancelled.",
    )
    pending: bool | None = Field(
        default=None,
        description="If true, orders are pending cancellation.",
    )


class CancelAllResponse(BaseSchema):
    """Combined response wrapper for CancelAll API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: CancelAllSuccess | None = Field(
        default=None,
        description="Success response data, present when order cancellation succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when order cancellation fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelAllResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelAllResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = CancelAllSuccess(
            count=result["count"],
            pending=result.get("pending"),
        )
        return cls(success=success_data)


class CancelAllOrdersAfterRequest(BaseSchema):
    """Schema for Kraken CancelAllOrdersAfter API request.

    This schema validates and prepares data for submission to Kraken's
    CancelAllOrdersAfter API endpoint, which provides a "Dead Man's Switch"
    mechanism to protect the client from network malfunction, extreme latency,
    or unexpected matching engine downtime.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - The 'timeout' parameter is REQUIRED and must be between 0-86400 seconds.
        - Set timeout to 0 to disable the timer.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Set dead man's switch to 60 seconds:
        >>> cancel_after = CancelAllOrdersAfterRequest(timeout=60)
        >>> data = cancel_after.to_api_dict()
        >>> response = client.request("CancelAllOrdersAfter", data=data)

        Disable the timer:
        >>> cancel_after = CancelAllOrdersAfterRequest(timeout=0)
        >>> response = client.request("CancelAllOrdersAfter", data=cancel_after.to_api_dict())

        Async usage:
        >>> cancel_after = CancelAllOrdersAfterRequest(timeout=60)
        >>> response = await client.arequest("CancelAllOrdersAfter", data=cancel_after.to_api_dict())
    """

    timeout: int = Field(
        ...,
        description="Duration (in seconds) to set/extend the timer. Must be 0-86400. Set to 0 to disable.",
    )

    @field_validator("timeout", mode="before")
    @classmethod
    def validate_timeout(cls, value: int | str) -> int:
        """Validate timeout is within allowed range.

        Args:
            value: Timeout value in seconds

        Returns:
            Validated timeout as integer

        Raises:
            ValueError: If timeout is outside allowed range
        """
        timeout = int(value)
        if timeout < 0 or timeout > 86400:
            raise ValueError(
                f"Timeout must be between 0 and 86400 seconds (24 hours), got {timeout}"
            )
        return timeout

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize cancel all orders after request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing cancel all orders
        after requests to the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API CancelAllOrdersAfter endpoint

        Example:
            >>> cancel_after = CancelAllOrdersAfterRequest(timeout=60)
            >>> data = cancel_after.to_api_dict()
            >>> # Pass to REST client
            >>> response = client.request("CancelAllOrdersAfter", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )


class CancelAllOrdersAfterSuccess(BaseSchema):
    """Successful CancelAllOrdersAfter response from Kraken API.

    Contains the current time and trigger time for the dead man's switch.
    """

    currentTime: str = Field(
        ...,
        description="Timestamp (RFC3339 format) at which the request was received.",
    )
    triggerTime: str = Field(
        ...,
        description="Timestamp (RFC3339 format) after which all orders will be cancelled, unless the timer is extended or disabled.",
    )


class CancelAllOrdersAfterResponse(BaseSchema):
    """Combined response wrapper for CancelAllOrdersAfter API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: CancelAllOrdersAfterSuccess | None = Field(
        default=None,
        description="Success response data, present when dead man's switch is set/reset successfully.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when request fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelAllOrdersAfterResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelAllOrdersAfterResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = CancelAllOrdersAfterSuccess(
            currentTime=result["currentTime"],
            triggerTime=result["triggerTime"],
        )
        return cls(success=success_data)


class GetWebSocketsTokenRequest(BaseSchema):
    """Schema for Kraken GetWebSocketsToken API request.

    This schema validates and prepares data for submission to Kraken's
    GetWebSocketsToken API endpoint, which generates an authentication token
    for establishing WebSocket connections. It is safe for concurrent async
    usage when properly serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - This endpoint requires API key authentication with "WebSocket interface - On"
          permission enabled.
        - The token should be used within 15 minutes of creation.
        - The token does not expire once a successful WebSocket connection with
          private subscription is established and maintained.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Get WebSocket authentication token:
        >>> ws_token_request = GetWebSocketsTokenRequest()
        >>> data = ws_token_request.to_api_dict()
        >>> response = client.request("GetWebSocketsToken", data=data)

        Async usage:
        >>> ws_token_request = GetWebSocketsTokenRequest()
        >>> response = await client.arequest("GetWebSocketsToken", data=ws_token_request.to_api_dict())
    """

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing requests to the
        REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API GetWebSocketsToken endpoint

        Example:
            >>> ws_token_request = GetWebSocketsTokenRequest()
            >>> data = ws_token_request.to_api_dict()
            >>> # Pass to REST client
            >>> response = client.request("GetWebSocketsToken", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )


class GetWebSocketsTokenSuccess(BaseSchema):
    """Successful GetWebSocketsToken response from Kraken API.

    Contains the WebSocket authentication token and expiration time.
    """

    token: str = Field(
        ...,
        description="WebSocket authentication token string.",
    )
    expires: int = Field(
        ...,
        description="Token expiration time in seconds (typically 900 = 15 minutes).",
    )


class GetWebSocketsTokenResponse(BaseSchema):
    """Combined response wrapper for GetWebSocketsToken API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: GetWebSocketsTokenSuccess | None = Field(
        default=None,
        description="Success response data, present when token generation succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when request fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "GetWebSocketsTokenResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            GetWebSocketsTokenResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = GetWebSocketsTokenSuccess(
            token=result["token"],
            expires=result["expires"],
        )
        return cls(success=success_data)


class BatchOrderItem(BaseSchema):
    """Schema for individual order within an AddOrderBatch request.

    This schema represents a single order in a batch submission. It contains
    the same fields as AddOrderRequest except for pair, asset_class, deadline,
    and only_validate which are specified at the batch level.

    Important Notes:
        - All orders in a batch must be for the same trading pair
        - Same validation rules as AddOrderRequest apply to each order
        - Batch-level validation occurs before submission to matching engine
        - Individual order failures during engine processing don't reject entire batch

    Usage Example:
        >>> order_item = BatchOrderItem(
        ...     ordertype="limit",
        ...     type="buy",
        ...     volume=1.5,
        ...     price="50000"
        ... )
    """

    userref: int | None = Field(
        default=None,
        description="User reference id. Mutually exclusive with cl_ord_id parameter.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Alphanumeric client order identifier. Mutually exclusive with userref parameter.",
    )
    ordertype: ORDER_TYPE = Field(..., description="The execution model of the order.")
    type: ORDER_DIRECTION = Field(..., description="Order direction (buy/sell).")
    volume: str | float | int = Field(
        ...,
        description="Order quantity in terms of the base asset.",
    )
    displayvol: str | float | int | None = Field(
        default=None,
        description="For iceberg orders only, visible quantity in the book.",
    )
    price: str | None = Field(
        default=None,
        description="Limit price for limit/iceberg orders; trigger price for stop-loss/take-profit orders.",
    )
    price2: str | None = Field(
        default=None,
        description="Limit price for stop-loss-limit and take-profit-limit orders.",
    )
    trigger: TRIGGER_TYPE | None = Field(
        default=None,
        description="Price signal used to trigger stop-loss and take-profit orders.",
    )
    leverage: str | int | None = Field(None, description="Amount of desired leverage.")
    reduce_only: bool = Field(
        default=False,
        description="If True, order will only reduce a currently open position.",
    )
    stptype: STP_TYPE | None = Field(
        default=None,
        description="Self Trade Prevention (STP) behavior.",
    )
    oflags: str | list[str] | set[str] | None = Field(
        default=None,
        description="Comma delimited list of order flags: 'post', 'fcib', 'fciq', 'viqc'.",
    )
    timeinforce: TIME_IN_FORCE | None = Field(
        default="GTC",
        description="Time-in-force of the order.",
    )
    starttm: str | None = Field(
        default="0",
        description="Scheduled start time.",
    )
    expiretm: str | None = Field(
        default="0",
        description="Expiry time on GTD orders.",
    )

    @field_validator("ordertype", mode="before")
    @classmethod
    def lowercase_order(cls, value: str) -> str:
        return value.lower().strip()

    @field_validator("volume", mode="before")
    @classmethod
    def string_volume(cls, value: str | float | int) -> str:
        return str(value)

    @field_validator("displayvol", mode="before")
    @classmethod
    def floor_display_volume(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_volume = float(info.data.get("volume"))
        floor_volume = order_volume / 15.0
        if float(value) > order_volume:
            return str(order_volume)
        elif float(value) < floor_volume:
            return str(floor_volume)
        else:
            return str(value)

    @field_validator("leverage", mode="before")
    @classmethod
    def string_leverage(cls, value: str | float | None) -> str | None:
        if value is None:
            return None
        return str(value)

    @field_validator("oflags", mode="before")
    @classmethod
    def concat_order_flags(cls, value: str | list[str] | set[str] | None) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            splits = value.split(",")
            if len(splits) > 1:
                value = set(splits)
            else:
                value = {value}
        elif isinstance(value, list):
            value = set(value)
        value = ORDER_FLAG_SET.intersection(value)
        return ",".join(value) if len(value) > 0 else None

    @field_validator("timeinforce", mode="before")
    @classmethod
    def capitalize_time_in_force(cls, value: str) -> str:
        return value.upper().strip()

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "BatchOrderItem":
        """Validate field dependencies for different order types."""
        if (
            self.ordertype in ["iceberg", "limit", "stop-loss", "take-profit", "trailing-stop"]
            and self.price is None
        ):
            raise ValueError(f"{self.ordertype} orders require 'price' field")
        if self.ordertype in ["stop-loss-limit", "take-profit-limit", "trailing-stop-limit"]:
            if self.price is None or self.price2 is None:
                raise ValueError(
                    f"{self.ordertype} orders require both 'price' and 'price2' fields"
                )
        if self.timeinforce == "GTD" and (self.expiretm is None or self.expiretm == "0"):
            raise ValueError("GTD (Good-Til-Date) orders require 'expiretm' field")
        if self.userref is not None and self.cl_ord_id is not None:
            raise ValueError("'userref' and 'cl_ord_id' are mutually exclusive")
        return self


class AddOrderBatchRequest(BaseSchema):
    """Schema for Kraken AddOrderBatch API request.

    This schema validates and prepares batch order data for submission to Kraken's
    AddOrderBatch API endpoint. Batch orders allow submitting 2-15 orders in a
    single request for the same trading pair.

    Important Notes:
        - Minimum 2 orders, maximum 15 orders per batch
        - All orders must be for the same trading pair
        - Validation is performed on the whole batch prior to submission
        - If an order fails validation, the whole batch will be rejected
        - On submission to engine, individual order failures don't reject entire batch
        - The 'nonce' parameter is automatically generated by the REST client
        - The 'deadline' parameter is NOT auto-generated during instantiation
        - Use to_api_dict() to serialize for API submission

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        Time-sensitive fields (nonce, deadline) are handled by the REST client
        at the last possible moment before request signing.

    Usage Examples:
        Batch of limit orders:
        >>> batch = AddOrderBatchRequest(
        ...     orders=[
        ...         BatchOrderItem(ordertype="limit", type="buy", volume=1.0, price="50000"),
        ...         BatchOrderItem(ordertype="limit", type="buy", volume=0.5, price="49000"),
        ...     ],
        ...     pair="XBTUSD"
        ... )
        >>> data = batch.to_api_dict()
        >>> response = client.request("AddOrderBatch", data=data)

        Mixed order types:
        >>> batch = AddOrderBatchRequest(
        ...     orders=[
        ...         BatchOrderItem(ordertype="market", type="buy", volume=1.0),
        ...         BatchOrderItem(ordertype="limit", type="sell", volume=1.0, price="55000"),
        ...         BatchOrderItem(ordertype="stop-loss", type="sell", volume=1.0, price="45000"),
        ...     ],
        ...     pair="XBTUSD"
        ... )

        Validation only:
        >>> batch = AddOrderBatchRequest(
        ...     orders=[...],
        ...     pair="XBTUSD",
        ...     validate=True
        ... )
    """

    orders: list[BatchOrderItem] = Field(
        ...,
        description="Array of orders (minimum 2, maximum 15).",
    )
    pair: str = Field(
        ..., description="Asset pair id or altname (all orders must be for this pair)."
    )
    asset_class: str | None = Field(
        None, description="Required to be set as 'tokenized_asset' for non-crypto pairs (xstocks)."
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the batch request.",
    )
    validate: bool = Field(
        default=False,
        description="If True, validates batch inputs without placing orders.",
    )

    @field_validator("orders", mode="after")
    @classmethod
    def validate_batch_size(cls, value: list[BatchOrderItem]) -> list[BatchOrderItem]:
        """Validate batch contains 2-15 orders."""
        if len(value) < 2:
            raise ValueError(f"Batch must contain at least 2 orders, got {len(value)}")
        if len(value) > 15:
            raise ValueError(f"Batch must contain at most 15 orders, got {len(value)}")
        return value

    @field_validator("deadline", mode="after")
    @classmethod
    def validate_deadline(cls, value: str | None) -> str | None:
        """Validate deadline format and timezone information."""
        if value is None:
            return None

        deadline = datetime.fromisoformat(value)
        if deadline.tzinfo is None:
            raise ValueError(
                "Deadline must include timezone information (RFC3339 format). "
                "Example: '2025-01-15T12:00:00+00:00' or use 'Z' for UTC."
            )

        # Validate deadline is bounded between 2-60 seconds from now
        now = utc_now()
        min_t, max_t = now + timedelta(seconds=2), now + timedelta(seconds=60)
        deadline_utc = deadline.astimezone(now.tzinfo)

        if deadline_utc < min_t:
            deadline_utc = min_t
        elif deadline_utc > max_t:
            deadline_utc = max_t

        return deadline_utc.isoformat()

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize batch request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing batch requests to
        the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API AddOrderBatch endpoint

        Example:
            >>> batch = AddOrderBatchRequest(orders=[...], pair="XBTUSD")
            >>> data = batch.to_api_dict()
            >>> response = client.request("AddOrderBatch", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )


class BatchOrderResult(BaseSchema):
    """Result for an individual order within an AddOrderBatch response.

    Represents the outcome of a single order in a batch submission.
    """

    txid: str | None = Field(
        default=None,
        description="Transaction ID for order (if order was added successfully).",
    )
    descr: dict | None = Field(
        default=None,
        description="Order description info (if order was added successfully).",
    )
    error: str | None = Field(
        default=None,
        description="Error description from individual order processing (if order failed).",
    )

    @property
    def is_success(self) -> bool:
        """Check if the individual order was successful."""
        return self.txid is not None and self.error is None


class AddOrderBatchSuccess(BaseSchema):
    """Successful AddOrderBatch response from Kraken API.

    Contains results for each order in the batch. The order of results matches
    the order of the request.
    """

    orders: list[BatchOrderResult] = Field(
        ...,
        description="Results for each order in the batch (order matches request order).",
    )


class AddOrderBatchResponse(BaseSchema):
    """Combined response wrapper for AddOrderBatch API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.

    Note: Even in success cases, individual orders may have errors. Check
    each BatchOrderResult for individual order outcomes.
    """

    success: AddOrderBatchSuccess | None = Field(
        default=None,
        description="Success response data, present when batch submission succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when batch validation fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the batch response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "AddOrderBatchResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AddOrderBatchResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")

        orders_data = result.get("orders", [])
        batch_results = []
        for order_data in orders_data:
            batch_result = BatchOrderResult(
                txid=order_data.get("txid"),
                descr=order_data.get("descr"),
                error=order_data.get("error"),
            )
            batch_results.append(batch_result)

        success_data = AddOrderBatchSuccess(orders=batch_results)
        return cls(success=success_data)


class CancelOrderBatchItem(BaseSchema):
    """Schema for individual order identifier in a CancelOrderBatch request.

    Represents a single order to cancel by either transaction ID (txid),
    user reference (userref), or client order ID (cl_ord_id).
    """

    txid: str | int | None = Field(
        default=None,
        description="Transaction ID (txid) or user reference (userref).",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Client order identifier.",
    )

    @field_validator("txid", mode="before")
    @classmethod
    def normalize_txid(cls, value: str | int | None) -> str | int | None:
        """Normalize txid - convert string integers to int, keep string txids as strings."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, str):
            try:
                return int(value)
            except ValueError:
                return value.strip()
        return value

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "CancelOrderBatchItem":
        """Validate that at least one identifier is provided."""
        if self.txid is None and self.cl_ord_id is None:
            raise ValueError("Either 'txid' or 'cl_ord_id' must be provided")
        if self.txid is not None and self.cl_ord_id is not None:
            raise ValueError("'txid' and 'cl_ord_id' are mutually exclusive")
        return self


class CancelOrderBatchRequest(BaseSchema):
    """Schema for Kraken CancelOrderBatch API request.

    This schema validates and prepares batch cancellation data for submission to
    Kraken's CancelOrderBatch API endpoint. Allows cancelling up to 50 orders in
    a single request.

    Important Notes:
        - Maximum 50 unique IDs/references per batch
        - Must provide either 'orders' or 'cl_ord_ids' (or both)
        - The 'nonce' parameter is automatically generated by the REST client
        - Use to_api_dict() to serialize for API submission

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Cancel by transaction IDs:
        >>> batch = CancelOrderBatchRequest(
        ...     orders=[
        ...         CancelOrderBatchItem(txid="OUF4EM-FRGI2-MQMWZD"),
        ...         CancelOrderBatchItem(txid="ABC123-DEF456-GHI789"),
        ...     ]
        ... )
        >>> response = client.request("CancelOrderBatch", data=batch.to_api_dict())

        Cancel by user references:
        >>> batch = CancelOrderBatchRequest(
        ...     orders=[
        ...         CancelOrderBatchItem(txid=12345),
        ...         CancelOrderBatchItem(txid=67890),
        ...     ]
        ... )

        Cancel by client order IDs:
        >>> batch = CancelOrderBatchRequest(
        ...     cl_ord_ids=["my-order-1", "my-order-2", "my-order-3"]
        ... )

        Mixed cancellation:
        >>> batch = CancelOrderBatchRequest(
        ...     orders=[CancelOrderBatchItem(txid="ABC-123")],
        ...     cl_ord_ids=["client-order-1"]
        ... )
    """

    orders: list[CancelOrderBatchItem] | None = Field(
        default=None,
        description="Array of order identifiers to cancel (up to 50 total).",
    )
    cl_ord_ids: list[str] | None = Field(
        default=None,
        description="Array of client order IDs to cancel (up to 50 total).",
    )

    @model_validator(mode="after")
    def validate_batch_constraints(self) -> "CancelOrderBatchRequest":
        """Validate batch size and that at least one identifier type is provided."""
        if self.orders is None and self.cl_ord_ids is None:
            raise ValueError("Either 'orders' or 'cl_ord_ids' must be provided")

        # Count total items
        total_items = 0
        if self.orders is not None:
            total_items += len(self.orders)
        if self.cl_ord_ids is not None:
            total_items += len(self.cl_ord_ids)

        if total_items > 50:
            raise ValueError(f"Batch must contain at most 50 total items, got {total_items}")

        return self

    def to_api_dict(self, **kwargs) -> dict[str, Any]:
        """Serialize cancel batch request to dict for Kraken API submission.

        This method handles proper field aliasing and exclusion of None values
        for API compatibility. Use this method when passing batch requests to
        the REST client.

        Args:
            exclude_none: If True, removes fields with None values from output.
                         Default is True for Kraken API compatibility.

        Returns:
            Dictionary suitable for Kraken API CancelOrderBatch endpoint

        Example:
            >>> batch = CancelOrderBatchRequest(orders=[...])
            >>> data = batch.to_api_dict()
            >>> response = client.request("CancelOrderBatch", data=data)
        """
        return self.model_dump(
            by_alias=kwargs.pop("by_alias", True),
            exclude_none=kwargs.pop("exclude_none", True),
            **kwargs,
        )


class CancelOrderBatchSuccess(BaseSchema):
    """Successful CancelOrderBatch response from Kraken API.

    Contains the number of orders cancelled.
    """

    count: int = Field(
        ...,
        description="Number of orders cancelled.",
    )


class CancelOrderBatchResponse(BaseSchema):
    """Combined response wrapper for CancelOrderBatch API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: CancelOrderBatchSuccess | None = Field(
        default=None,
        description="Success response data, present when batch cancellation succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when batch cancellation fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelOrderBatchResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelOrderBatchResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = CancelOrderBatchSuccess(count=result["count"])
        return cls(success=success_data)
