import json
from datetime import datetime, timedelta
from typing import Literal

from pydantic import BaseModel as BaseSchema
from pydantic import Field, field_validator

from kraken.constants import LATENCY_TOLERANCE
from kraken.utilities import utc_now

ORDER_TYPE = Literal[
    "market",
    "limit",
    "iceberg",
    "stop-loss",
    "take-profit",
    "stop-loss-limit",
    "take-profit-limit",
    "trailing-stop",
    "trailing-stop-limit",
    "settle-position",
]
ORDER_DIRECTION = Literal["buy", "sell"]
ORDER_FLAG_SET = set(["post", "fcib", "fciq", "viqc"])
TRIGGER_TYPE = Literal["index", "last"]
STP_TYPE = Literal["cancel-newest", "cancel-oldest", "cancel-both"]
TIME_IN_FORCE = Literal["GTC", "IOC", "GTD", "PO"]


class ResponseErrorSchema(BaseSchema):
    """Error response from Kraken API.

    Contains error messages when order placement fails.
    """

    error: list[str] = Field(
        ...,
        description="List of error messages from the API.",
    )


class AddOrderRequest(BaseSchema):
    """Schema for Kraken AddOrder API request.

    Note: The nonce parameter is automatically generated by the REST client
    at request signing time to prevent race conditions in concurrent operations.
    Do not manually set nonce values in this schema.

    Warning: This schema is safe for concurrent async usage when used with
    the KrakenRESTClient, which handles nonce generation atomically.
    """

    userref: int | None = Field(
        default=None,
        description="This is an optional non-unique, numeric identifier for user metadata tracking. This field is mutually exclusive with `cl_ord_id` parameter.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Adds an alphanumeric client order identifier which uniquely identifies an open order for each client (long/short UUID or 18-ascii char). This field is mutually exclusive with `userref` parameter.",
    )
    ordertype: ORDER_TYPE = Field(..., description="The execution model of the order.")
    type: ORDER_DIRECTION = Field(..., description="Order direction (buy/sell).")
    volume: str | float | int = Field(
        ...,
        description="Order quantity in terms of the base asset; can be specified as 0 for closing margin orders to automatically fill the requisite quantity.",
    )
    displayvol: str | float | int | None = Field(
        default=None,
        description="For 'iceberg' orders only, it defines the quantity to show in the book while the rest of order quantity remains hidden. Minimum value is 1/15 of volume.",
    )
    pair: str = Field(..., description="Asset pair `id` or `altname`.")
    asset_class: str | None = Field(
        None, description="Required to be set as 'tokenized_asset' for non-crypto pairs (xstocks)."
    )
    price: str | None = Field(
        default=None,
        description="Limit price for 'limit' and 'iceberg' orders; trigger price for 'stop-loss', 'stop-loss-limit', 'take-profit', 'take-profit-limit', 'trailing-stop' and 'trailing-stop-limit' orders.",
    )
    price2: str | None = Field(
        default=None,
        description="Limit price for 'stop-loss-limit', 'take-profit-limit' and 'trailing-stop-limit' orders.",
    )
    trigger: TRIGGER_TYPE | None = Field(
        default=None,
        description="Price signal used to trigger 'stop-loss', 'stop-loss-limit', 'take-profit', 'take-profit-limit', 'trailing-stop' and 'trailing-stop-limit' orders.",
    )
    leverage: str | int | None = Field(None, description="Amount of desired leverage.")
    reduce_only: bool | None = Field(
        default=False,
        description="If `True`, order will only reduce a currently open position, not increase it or open a new position.",
    )
    stptype: STP_TYPE | None = Field(
        default=None,
        description="Self Trade Prevention (STP) behavior. If None, uses Kraken's default. Options: 'cancel-newest', 'cancel-oldest', 'cancel-both'.",
    )
    oflags: str | list[str] | set[str] | None = Field(
        default=None,
        description="Comma delimited list of order flags: 'post', 'fcib', 'fciq', 'viqc'.",
    )
    timeinforce: TIME_IN_FORCE | None = Field(
        default="GTC",
        description="Time-in-force of the order to specify how long it should remain in the order book before being cancelled.",
    )
    starttm: str | None = Field(
        default="0",
        description="Scheduled start time, can be specified as an absolute timestamp or as a number of seconds in the future.",
    )
    expiretm: str | None = Field(
        default="0",
        description="Expiry time on GTD orders can be set up to one month in future, it is specified as an absolute timestamp or as a number of seconds from now.",
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the new order request, in presence of latency or order queueing.",
    )
    only_validate: bool = Field(
        default=False,
        description="If True, validates order inputs without placing the order. Set to True for testing order parameters without execution.",
        validation_alias="validate",  # Match Kraken API field name
    )
    close_ordertype: ORDER_TYPE | None = Field(
        default=None,
        description="Conditional close order type for positions. Used with 'close_price' and optionally 'close_price2' to create an OCO (One-Cancels-Other) order.",
    )
    close_price: str | None = Field(
        default=None,
        description="Conditional close order price. Required when 'close_ordertype' is specified.",
    )
    close_price2: str | None = Field(
        default=None,
        description="Conditional close order secondary price for stop-loss-limit or take-profit-limit orders.",
    )

    @field_validator("ordertype", mode="before")
    @classmethod
    def lowercase_order(cls, value: str) -> str:
        return value.lower().strip()

    @field_validator("volume", mode="before")
    @classmethod
    def string_volume(cls, value: str | float | int) -> str:
        return str(value)

    @field_validator("displayvol", mode="before")
    @classmethod
    def floor_display_volume(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_volume = float(info.data.get("volume"))
        floor_volume = order_volume / 15.0
        if float(value) > order_volume:
            return str(order_volume)
        elif float(value) < floor_volume:
            return str(floor_volume)
        else:
            return str(value)

    @field_validator("leverage", mode="before")
    @classmethod
    def string_leverage(cls, value: str | float | None) -> str | None:
        if value is None:
            return None
        return str(value)

    @field_validator("oflags", mode="before")
    @classmethod
    def concat_order_flags(cls, value: str | list[str] | set[str] | None) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            splits = value.split(",")
            if len(splits) > 1:
                value = set(splits)
            else:
                value = {value}
        elif isinstance(value, list):
            value = set(value)
        value = ORDER_FLAG_SET.intersection(value)
        return ",".join(value) if len(value) > 0 else None

    @field_validator("timeinforce", mode="before")
    @classmethod
    def capitalize_time_in_force(cls, value: str) -> str:
        return value.upper().strip()

    @field_validator("deadline", mode="after")
    @classmethod
    def bound_deadline(cls, value: str | None, latency_tolerance: int = LATENCY_TOLERANCE) -> str:
        now = utc_now()
        min_t, max_t = now + timedelta(seconds=2), now + timedelta(seconds=60)
        if value is None:
            deadline = now + timedelta(seconds=latency_tolerance)
        else:
            deadline = datetime.fromisoformat(value)
            if deadline.tzinfo is None:
                raise ValueError(
                    "Deadline must include timezone information (RFC3339 format). "
                    "Example: '2025-01-15T12:00:00+00:00' or use 'Z' for UTC."
                )
            deadline = deadline.astimezone(now.tzinfo)
            if deadline < min_t:
                deadline = min_t
            elif deadline > max_t:
                deadline = max_t
        return deadline.isoformat()


class AddOrderSuccess(BaseSchema):
    """Successful AddOrder response from Kraken API.

    Contains order details and transaction IDs when an order is successfully
    placed or validated.
    """

    txid: list[str] = Field(
        ...,
        description="18-character transaction IDs for the order(s) placed.",
    )
    descr: dict = Field(
        ...,
        description="Order description containing 'order' and optionally 'close' fields.",
    )

    @property
    def order_description(self) -> str:
        """Get the order description string."""
        return self.descr.get("order", "")

    @property
    def close_description(self) -> str | None:
        """Get the conditional close order description, if any."""
        return self.descr.get("close")


class AddOrderResponse(BaseSchema):
    """Combined response wrapper for AddOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    success: AddOrderSuccess | None = Field(
        default=None,
        description="Success response data, present when order placement succeeds.",
    )
    error: ResponseErrorSchema | None = Field(
        default=None,
        description="Error response data, present when order placement fails.",
    )

    @property
    def is_success(self) -> bool:
        """Check if the response indicates success."""
        return self.success is not None

    @classmethod
    def from_response(cls, response: dict | str) -> "AddOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AddOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(error=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = AddOrderSuccess(
            txid=result["txid"],
            descr=result["descr"],
        )
        return cls(success=success_data)
