import json
from typing import Literal

from pydantic import AliasChoices, Field, field_validator, model_validator

from kraken.rest.schema import validators
from kraken.rest.schema.base import (
    BaseRequestSchema,
    BaseResponseWrapper,
    BaseSchema,
    ResponseErrorSchema,
)

ORDER_TYPE = Literal[
    "market",
    "limit",
    "iceberg",
    "stop-loss",
    "take-profit",
    "stop-loss-limit",
    "take-profit-limit",
    "trailing-stop",
    "trailing-stop-limit",
    "settle-position",
]
ORDER_DIRECTION = Literal["buy", "sell"]
ORDER_FLAG = Literal["post", "fcib", "fciq", "viqc"]
TRIGGER_TYPE = Literal["index", "last"]
STP_TYPE = Literal["cancel-newest", "cancel-oldest", "cancel-both"]
TIME_IN_FORCE = Literal["GTC", "IOC", "GTD", "PO"]


class OrderIdentifierMixin(BaseSchema):
    """Mixin for schemas that identify orders by txid or cl_ord_id.

    Provides common fields and validation for mutual exclusivity.
    """

    txid: str | int | None = Field(
        default=None,
        description="Transaction ID (txid) or user reference (userref).",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Client order identifier.",
    )

    @field_validator("txid", mode="before")
    @classmethod
    def normalize_txid(cls, value: str | int | None) -> str | int | None:
        """Normalize txid - convert string integers to int, keep string txids as strings."""
        return validators.normalize_txid(value)

    @model_validator(mode="after")
    def validate_identifier_mutual_exclusivity(self) -> "OrderIdentifierMixin":
        """Validate that txid and cl_ord_id are mutually exclusive."""
        if self.txid is None and self.cl_ord_id is None:
            raise ValueError("Either 'txid' or 'cl_ord_id' must be provided")
        if self.txid is not None and self.cl_ord_id is not None:
            raise ValueError("'txid' and 'cl_ord_id' are mutually exclusive")
        return self


class AddOrderRequest(BaseRequestSchema):
    """Schema for Kraken AddOrder API request.

    This schema validates and prepares order data for submission to Kraken's
    AddOrder API endpoint. It is safe for concurrent async usage when properly
    serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - The 'deadline' parameter is NOT auto-generated during instantiation
          to prevent stale timestamps in async scenarios. The REST client
          will generate it at request time if None.
        - Use to_api_dict() to serialize for API submission (handles field
          aliasing like 'only_validate' -> 'validate').

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        Time-sensitive fields (nonce, deadline) are handled by the REST client
        at the last possible moment before request signing.

    Usage Examples:
        Basic market order:
        >>> order = AddOrderRequest(
        ...     ordertype="market",
        ...     type="buy",
        ...     volume=1.5,
        ...     pair="XBTUSD"
        ... )
        >>> data = order.to_api_dict()
        >>> response = client.request("AddOrder", data=data)

        Limit order with custom deadline:
        >>> from datetime import datetime, timedelta, timezone
        >>> deadline = (datetime.now(timezone.utc) + timedelta(seconds=10)).isoformat()
        >>> order = AddOrderRequest(
        ...     ordertype="limit",
        ...     type="sell",
        ...     volume=0.5,
        ...     pair="ETHUSD",
        ...     price="2000.50",
        ...     deadline=deadline
        ... )

        Validation only (no execution):
        >>> order = AddOrderRequest(
        ...     ordertype="limit",
        ...     type="buy",
        ...     volume=1,
        ...     pair="XBTUSD",
        ...     price="50000",
        ...     only_validate=True  # Test order validity without placing
        ... )

        Async usage (deadline computed at request time):
        >>> order = AddOrderRequest(
        ...     ordertype="market",
        ...     type="buy",
        ...     volume=1,
        ...     pair="XBTUSD"
        ... )
        >>> # Deadline remains None during queueing/delays
        >>> await asyncio.sleep(5)
        >>> # REST client will compute deadline at signing time
        >>> response = await client.arequest("AddOrder", data=order.to_api_dict())
    """

    userref: int | None = Field(
        default=None,
        description="This is an optional non-unique, numeric identifier for user metadata tracking. This field is mutually exclusive with `cl_ord_id` parameter.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Adds an alphanumeric client order identifier which uniquely identifies an open order for each client (long/short UUID or 18-ascii char). This field is mutually exclusive with `userref` parameter.",
    )
    ordertype: ORDER_TYPE = Field(..., description="The execution model of the order.")
    type: ORDER_DIRECTION = Field(..., description="Order direction (buy/sell).")
    volume: str | float | int = Field(
        ...,
        description="Order quantity in terms of the base asset; can be specified as 0 for closing margin orders to automatically fill the requisite quantity.",
    )
    displayvol: str | float | int | None = Field(
        default=None,
        description="For 'iceberg' orders only, it defines the quantity to show in the book while the rest of order quantity remains hidden. Minimum value is 1/15 of volume.",
    )
    pair: str = Field(..., description="Asset pair `id` or `altname`.")
    asset_class: str | None = Field(
        None, description="Required to be set as 'tokenized_asset' for non-crypto pairs (xstocks)."
    )
    price: str | None = Field(
        default=None,
        description="Limit price for 'limit' and 'iceberg' orders; trigger price for 'stop-loss', 'stop-loss-limit', 'take-profit', 'take-profit-limit', 'trailing-stop' and 'trailing-stop-limit' orders.",
    )
    price2: str | None = Field(
        default=None,
        description="Limit price for 'stop-loss-limit', 'take-profit-limit' and 'trailing-stop-limit' orders.",
    )
    trigger: TRIGGER_TYPE | None = Field(
        default=None,
        description="Price signal used to trigger 'stop-loss', 'stop-loss-limit', 'take-profit', 'take-profit-limit', 'trailing-stop' and 'trailing-stop-limit' orders.",
    )
    leverage: str | int | None = Field(None, description="Amount of desired leverage.")
    reduce_only: bool = Field(
        default=False,
        description="If `True`, order will only reduce a currently open position, not increase it or open a new position.",
    )
    stptype: STP_TYPE | None = Field(
        default=None,
        description="Self Trade Prevention (STP) behavior. If None, uses Kraken's default. Options: 'cancel-newest', 'cancel-oldest', 'cancel-both'.",
    )
    oflags: str | ORDER_FLAG | list[ORDER_FLAG] | set[ORDER_FLAG] | None = Field(
        default=None,
        description="Comma delimited list of order flags: 'post', 'fcib', 'fciq', 'viqc'.",
    )
    timeinforce: TIME_IN_FORCE | None = Field(
        default="GTC",
        description="Time-in-force of the order to specify how long it should remain in the order book before being cancelled.",
    )
    starttm: str | None = Field(
        default="0",
        description="Scheduled start time, can be specified as an absolute timestamp or as a number of seconds in the future.",
    )
    expiretm: str | None = Field(
        default="0",
        description="Expiry time on GTD orders can be set up to one month in future, it is specified as an absolute timestamp or as a number of seconds from now.",
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the new order request, in presence of latency or order queueing.",
    )
    only_validate: bool = Field(
        default=False,
        description="If True, validates order inputs without placing the order. Set to True for testing order parameters without execution.",
        validation_alias=AliasChoices("only_validate", "validate"),  # Accept both names
        serialization_alias="validate",  # Send as 'validate' to API
    )
    close_ordertype: ORDER_TYPE | None = Field(
        default=None,
        description="Conditional close order type for positions. Used with 'close_price' and optionally 'close_price2' to create an OCO (One-Cancels-Other) order.",
    )
    close_price: str | None = Field(
        default=None,
        description="Conditional close order price. Required when 'close_ordertype' is specified.",
    )
    close_price2: str | None = Field(
        default=None,
        description="Conditional close order secondary price for stop-loss-limit or take-profit-limit orders.",
    )

    @field_validator("ordertype", mode="before")
    @classmethod
    def lowercase_order(cls, value: str) -> str:
        return validators.validate_ordertype(value)

    @field_validator("volume", mode="before")
    @classmethod
    def string_volume(cls, value: str | float | int) -> str:
        return validators.validate_volume(value)

    @field_validator("displayvol", mode="before")
    @classmethod
    def floor_display_volume(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_volume = float(info.data.get("volume"))
        return validators.validate_display_volume(value, order_volume)

    @field_validator("leverage", mode="before")
    @classmethod
    def string_leverage(cls, value: str | int | None) -> str | None:
        return validators.validate_leverage(value)

    @field_validator("oflags", mode="before")
    @classmethod
    def concat_order_flags(cls, value: str | list[str] | set[str] | None) -> str | None:
        return validators.validate_order_flags(value)

    @field_validator("timeinforce", mode="before")
    @classmethod
    def capitalize_time_in_force(cls, value: str) -> str:
        return validators.validate_time_in_force(value)

    @field_validator("deadline", mode="after")
    @classmethod
    def validate_deadline(cls, value: str | None) -> str | None:
        """Validate deadline format and timezone information.

        Note: Deadline is NOT auto-generated here to prevent race conditions.
        The REST client will generate the deadline at request signing time
        if None is provided, ensuring accurate timing for async operations.
        """
        return validators.validate_deadline(value)

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "AddOrderRequest":
        """Validate field dependencies for different order types."""
        if (
            self.ordertype in ["iceberg", "limit", "stop-loss", "take-profit", "trailing-stop"]
            and self.price is None
        ):
            raise ValueError(f"{self.ordertype} orders require 'price' field")
        if self.ordertype in ["stop-loss-limit", "take-profit-limit", "trailing-stop-limit"]:
            if self.price is None or self.price2 is None:
                raise ValueError(
                    f"{self.ordertype} orders require both 'price' and 'price2' fields"
                )
        if self.close_ordertype is not None and self.close_price is None:
            raise ValueError("Conditional close orders require 'close_price' field")
        if self.close_ordertype in ["stop-loss-limit", "take-profit-limit"]:
            if self.close_price2 is None:
                raise ValueError(
                    f"Conditional close {self.close_ordertype} orders require 'close_price2' field"
                )
        if self.timeinforce == "GTD" and (self.expiretm is None or self.expiretm == "0"):
            raise ValueError("GTD (Good-Til-Date) orders require 'expiretm' field")
        if self.userref is not None and self.cl_ord_id is not None:
            raise ValueError("'userref' and 'cl_ord_id' are mutually exclusive")
        return self


class AddOrderSuccess(BaseSchema):
    """Successful AddOrder response from Kraken API.

    Contains order details and transaction IDs when an order is successfully
    placed or validated.
    """

    txid: list[str] = Field(
        ...,
        description="18-character transaction IDs for the order(s) placed.",
    )
    descr: dict = Field(
        ...,
        description="Order description containing 'order' and optionally 'close' fields.",
    )

    @property
    def order_description(self) -> str:
        """Get the order description string."""
        return self.descr.get("order", "")

    @property
    def close_description(self) -> str | None:
        """Get the conditional close order description, if any."""
        return self.descr.get("close")


class AddOrderResponse(BaseResponseWrapper[AddOrderSuccess]):
    """Combined response wrapper for AddOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "AddOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AddOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = AddOrderSuccess(
            txid=result["txid"],
            descr=result["descr"],
        )
        return cls(success=success_data)


class AmendOrderRequest(BaseRequestSchema):
    """Schema for Kraken AmendOrder API request (Atomic Amend Model).

    The atomic amend model is a fast, single-phase transaction that enables clients
    to modify order parameters in-place within the trading engine. A single order will
    be maintained across the lifetime of amend transactions. Each amended order will:
    - Keep the same order identifier assigned by Kraken and/or client
    - Reuse the execution information on the order for any previous fills
    - Keep queue priority in the order book where possible

    This schema validates and prepares order amendment data for submission to
    Kraken's AmendOrder API endpoint. It is safe for concurrent async usage when
    properly serialized using the to_api_dict() method.

    Important Behavioral Notes:
        - Amending Below Fill Quantity: To keep the behavior consistent with the client
          intentions (not to trade above given order quantity), amending the order quantity
          to below the filled quantity will amend the order to match the filled quantity and
          the remaining order is cancelled back to the client.
        - Rate Limits: In terms of rate limits, if an order is cancelled by an amend it has
          the standard cancel rate limit penalty.
        - Supported Fields: The atomic amend model allows modification of price, quantity,
          display quantity on iceberg orders, and order trigger price fields. Single or
          multiple parameters can be amended in a transaction.
        - Immutable Fields: At any time, if the order type, margin characteristics or the
          lifetime attributes (start, end, time-in-force) need to be changed then cancel
          the existing order and reissue a new one.

    Authentication & Authorization:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - The 'deadline' parameter is NOT auto-generated during instantiation
          to prevent stale timestamps in async scenarios. The REST client
          will generate it at request time if None.
        - Either 'txid' or 'cl_ord_id' must be provided to identify the order.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        Time-sensitive fields (nonce, deadline) are handled by the REST client
        at the last possible moment before request signing.

    Usage Examples:
        Amend order quantity by txid:
        >>> amend = AmendOrderRequest(
        ...     txid="OUF4EM-FRGI2-MQMWZD",
        ...     order_qty=2.5
        ... )
        >>> data = amend.to_api_dict()
        >>> response = client.request("AmendOrder", data=data)

        Amend limit price by client order ID:
        >>> amend = AmendOrderRequest(
        ...     cl_ord_id="my-order-123",
        ...     limit_price="51000.50"
        ... )
        >>> response = client.request("AmendOrder", data=amend.to_api_dict())

        Amend with relative pricing:
        >>> amend = AmendOrderRequest(
        ...     txid="ABC-123",
        ...     limit_price="+100",  # Add 100 to current reference price
        ...     trigger_price="-50%"  # Subtract 50% from reference price
        ... )

        Amend iceberg order display quantity:
        >>> amend = AmendOrderRequest(
        ...     txid="OUF4EM-FRGI2-MQMWZD",
        ...     display_qty=5.0,
        ...     pair="XBTUSD"
        ... )

        Async usage (deadline computed at request time):
        >>> amend = AmendOrderRequest(
        ...     txid="OUF4EM-FRGI2-MQMWZD",
        ...     order_qty=1.5
        ... )
        >>> # Deadline remains None during queueing/delays
        >>> await asyncio.sleep(5)
        >>> # REST client will compute deadline at signing time
        >>> response = await client.arequest("AmendOrder", data=amend.to_api_dict())
    """

    txid: str | None = Field(
        default=None,
        description="The Kraken identifier for the order to be amended. Either txid or cl_ord_id is required.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="The client identifier for the order to be amended. Either txid or cl_ord_id is required.",
    )
    order_qty: str | float | int | None = Field(
        default=None,
        description="The new order quantity in terms of the base asset.",
    )
    display_qty: str | float | int | None = Field(
        default=None,
        description="For iceberg orders only, it defines the new quantity to show in the book while the rest of order quantity remains hidden. Minimum value is 1/15 of remaining order quantity.",
    )
    limit_price: str | None = Field(
        default=None,
        description="The new limit price restriction on the order (for order types that support limit price only). Supports relative pricing: +/- prefix to add/subtract from reference price, % suffix for percentage adjustments.",
    )
    trigger_price: str | None = Field(
        default=None,
        description="The new trigger price to activate the order (for triggered order types only). Supports relative pricing: +/- prefix to add/subtract from reference price, % suffix for percentage adjustments.",
    )
    pair: str | None = Field(
        default=None,
        description="The pair is required on amends for non-crypto pairs (xstocks). Provide the pair symbol for tokenized assets.",
    )
    post_only: bool = Field(
        default=False,
        description="An optional flag for limit_price amends. If true, the limit price change will be rejected if the order cannot be posted passively in the book.",
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the amend request, in presence of latency or order queueing.",
    )

    @field_validator("order_qty", mode="before")
    @classmethod
    def string_order_qty(cls, value: str | float | int | None) -> str | None:
        return validators.validate_volume(value) if value is not None else None

    @field_validator("display_qty", mode="before")
    @classmethod
    def floor_display_qty(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_qty = info.data.get("order_qty")
        if order_qty is not None:
            return validators.validate_display_volume(value, float(order_qty))
        return str(value)

    @field_validator("deadline", mode="after")
    @classmethod
    def validate_deadline(cls, value: str | None) -> str | None:
        """Validate deadline format and timezone information.

        Note: Deadline is NOT auto-generated here to prevent race conditions.
        The REST client will generate the deadline at request signing time
        if None is provided, ensuring accurate timing for async operations.
        """
        return validators.validate_deadline(value)

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "AmendOrderRequest":
        """Validate field dependencies for amend requests."""
        if self.txid is None and self.cl_ord_id is None:
            raise ValueError("Either 'txid' or 'cl_ord_id' must be provided")
        if self.txid is not None and self.cl_ord_id is not None:
            raise ValueError("'txid' and 'cl_ord_id' are mutually exclusive")
        return self


class AmendOrderSuccess(BaseSchema):
    """Successful AmendOrder response from Kraken API.

    Contains the unique amend transaction identifier when an order amendment
    is successfully processed.
    """

    amend_id: str = Field(
        ...,
        description="The unique Kraken identifier generated for this amend transaction.",
    )


class AmendOrderResponse(BaseResponseWrapper[AmendOrderSuccess]):
    """Combined response wrapper for AmendOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "AmendOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AmendOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = AmendOrderSuccess(amend_id=result["amend_id"])
        return cls(success=success_data)


class CancelOrderRequest(BaseRequestSchema, OrderIdentifierMixin):
    """Schema for Kraken CancelOrder API request.

    This schema validates and prepares order cancellation data for submission to
    Kraken's CancelOrder API endpoint. It is safe for concurrent async usage when
    properly serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - Either 'txid' or 'cl_ord_id' must be provided to identify the order(s).
        - The 'txid' field accepts either a string (single order ID), integer
          (user reference), or string representation of an integer.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Cancel by transaction ID:
        >>> cancel = CancelOrderRequest(txid="OUF4EM-FRGI2-MQMWZD")
        >>> data = cancel.to_api_dict()
        >>> response = client.request("CancelOrder", data=data)

        Cancel by user reference (integer):
        >>> cancel = CancelOrderRequest(txid=12345)
        >>> response = client.request("CancelOrder", data=cancel.to_api_dict())

        Cancel by client order ID:
        >>> cancel = CancelOrderRequest(cl_ord_id="my-order-123")
        >>> response = client.request("CancelOrder", data=cancel.to_api_dict())

        Async usage:
        >>> cancel = CancelOrderRequest(txid="OUF4EM-FRGI2-MQMWZD")
        >>> await asyncio.sleep(5)
        >>> # REST client will compute nonce at signing time
        >>> response = await client.arequest("CancelOrder", data=cancel.to_api_dict())
    """

    pass


class CancelOrderSuccess(BaseSchema):
    """Successful CancelOrder response from Kraken API.

    Contains information about the number of orders cancelled and whether
    cancellation is pending.
    """

    count: int = Field(
        ...,
        description="Number of orders cancelled.",
    )
    pending: bool | None = Field(
        default=None,
        description="If true, orders are pending cancellation.",
    )


class CancelOrderResponse(BaseResponseWrapper[CancelOrderSuccess]):
    """Combined response wrapper for CancelOrder API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelOrderResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = CancelOrderSuccess(
            count=result["count"],
            pending=result.get("pending"),
        )
        return cls(success=success_data)


class CancelAllRequest(BaseRequestSchema):
    """Schema for Kraken CancelAll and CancelAllOrdersAfter API requests.

    This schema validates and prepares data for submission to Kraken's
    CancelAll API endpoint (cancels all open orders) or CancelAllOrdersAfter
    endpoint (Dead Man's Switch), depending on whether timeout is provided.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - If timeout is None, routes to CancelAll endpoint (immediate cancellation).
        - If timeout is provided (0-86400), routes to CancelAllOrdersAfter endpoint.
        - Set timeout to 0 to disable the Dead Man's Switch timer.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Cancel all open orders immediately:
        >>> cancel_all = CancelAllRequest()
        >>> data = cancel_all.to_api_dict()
        >>> response = client.request("CancelAll", data=data)

        Set Dead Man's Switch to 60 seconds:
        >>> cancel_all = CancelAllRequest(timeout=60)
        >>> data = cancel_all.to_api_dict()
        >>> response = client.request("CancelAllOrdersAfter", data=data)

        Disable the Dead Man's Switch timer:
        >>> cancel_all = CancelAllRequest(timeout=0)
        >>> response = client.request("CancelAllOrdersAfter", data=cancel_all.to_api_dict())

        Async usage:
        >>> cancel_all = CancelAllRequest(timeout=120)
        >>> response = await client.arequest("CancelAllOrdersAfter", data=cancel_all.to_api_dict())
    """

    timeout: int | None = Field(
        default=None,
        description="Duration (in seconds) to set/extend the timer. Must be 0-86400. Set to 0 to disable. If None, cancels all orders immediately.",
    )

    @field_validator("timeout", mode="before")
    @classmethod
    def validate_timeout(cls, value: int | str | None) -> int | None:
        """Validate timeout is within allowed range or None.

        Args:
            value: Timeout value in seconds or None

        Returns:
            Validated timeout as integer or None

        Raises:
            ValueError: If timeout is outside allowed range
        """
        if value is None:
            return None
        return validators.validate_timeout(value)


class CancelAllSuccess(BaseSchema):
    """Successful CancelAll or CancelAllOrdersAfter response from Kraken API.

    Contains information about the number of orders cancelled (for CancelAll)
    or Dead Man's Switch timing information (for CancelAllOrdersAfter).

    Response fields depend on which endpoint was called:
    - CancelAll endpoint: returns count and optionally pending
    - CancelAllOrdersAfter endpoint: returns current_time and trigger_time
    """

    # CancelAll response fields
    count: int | None = Field(
        default=None,
        description="Number of orders cancelled (CancelAll endpoint only).",
    )
    pending: bool | None = Field(
        default=None,
        description="If true, orders are pending cancellation (CancelAll endpoint only).",
    )

    # CancelAllOrdersAfter response fields
    current_time: str | None = Field(
        default=None,
        alias="currentTime",
        validation_alias="currentTime",
        description="Timestamp (RFC3339 format) at which the request was received (CancelAllOrdersAfter endpoint only).",
    )
    trigger_time: str | None = Field(
        default=None,
        alias="triggerTime",
        validation_alias="triggerTime",
        description="Timestamp (RFC3339 format) after which all orders will be cancelled (CancelAllOrdersAfter endpoint only).",
    )

    @model_validator(mode="after")
    def validate_response_type(self) -> "CancelAllSuccess":
        """Validate that response contains fields from exactly one endpoint type."""
        has_cancel_all_fields = self.count is not None
        has_cancel_all_after_fields = (
            self.current_time is not None or self.trigger_time is not None
        )

        if not has_cancel_all_fields and not has_cancel_all_after_fields:
            raise ValueError(
                "Response must contain either CancelAll fields (count) or "
                "CancelAllOrdersAfter fields (currentTime, triggerTime)"
            )

        if has_cancel_all_fields and has_cancel_all_after_fields:
            raise ValueError(
                "Response cannot contain both CancelAll and CancelAllOrdersAfter fields"
            )

        return self


class CancelOrderResponse(BaseResponseWrapper[CancelAllSuccess]):
    """Combined response wrapper for CancelAll and CancelAllOrdersAfter API calls.

    This wrapper handles both success and error cases from the Kraken API
    for both the CancelAll endpoint (immediate cancellation) and the
    CancelAllOrdersAfter endpoint (Dead Man's Switch).

    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelOrderResponse":
        """Parse a Kraken API response into the appropriate response model.

        Handles responses from both CancelAll and CancelAllOrdersAfter endpoints.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelAllResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")

        # Construct success data with all possible fields
        # The CancelAllSuccess validator will ensure only one set is present
        success_data = CancelAllSuccess(
            count=result.get("count"),
            pending=result.get("pending"),
            currentTime=result.get("currentTime"),
            triggerTime=result.get("triggerTime"),
        )
        return cls(success=success_data)


class GetWebSocketsTokenRequest(BaseRequestSchema):
    """Schema for Kraken GetWebSocketsToken API request.

    This schema validates and prepares data for submission to Kraken's
    GetWebSocketsToken API endpoint, which generates an authentication token
    for establishing WebSocket connections. It is safe for concurrent async
    usage when properly serialized using the to_api_dict() method.

    Important Notes:
        - The 'nonce' parameter is automatically generated by the REST client
          at request signing time to prevent race conditions.
        - This endpoint requires API key authentication with "WebSocket interface - On"
          permission enabled.
        - The token should be used within 15 minutes of creation.
        - The token does not expire once a successful WebSocket connection with
          private subscription is established and maintained.
        - Use to_api_dict() to serialize for API submission.

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Get WebSocket authentication token:
        >>> ws_token_request = GetWebSocketsTokenRequest()
        >>> data = ws_token_request.to_api_dict()
        >>> response = client.request("GetWebSocketsToken", data=data)

        Async usage:
        >>> ws_token_request = GetWebSocketsTokenRequest()
        >>> response = await client.arequest("GetWebSocketsToken", data=ws_token_request.to_api_dict())
    """

    pass


class GetWebSocketsTokenSuccess(BaseSchema):
    """Successful GetWebSocketsToken response from Kraken API.

    Contains the WebSocket authentication token and expiration time.
    """

    token: str = Field(
        ...,
        description="WebSocket authentication token string.",
    )
    expires: int = Field(
        ...,
        description="Token expiration time in seconds (typically 900 = 15 minutes).",
    )


class GetWebSocketsTokenResponse(BaseResponseWrapper[GetWebSocketsTokenSuccess]):
    """Combined response wrapper for GetWebSocketsToken API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "GetWebSocketsTokenResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            GetWebSocketsTokenResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = GetWebSocketsTokenSuccess(
            token=result["token"],
            expires=result["expires"],
        )
        return cls(success=success_data)


class BatchOrderItem(BaseSchema):
    """Schema for individual order within an AddOrderBatch request.

    This schema represents a single order in a batch submission. It contains
    the same fields as AddOrderRequest except for pair, asset_class, deadline,
    and only_validate which are specified at the batch level.

    Important Notes:
        - All orders in a batch must be for the same trading pair
        - Same validation rules as AddOrderRequest apply to each order
        - Batch-level validation occurs before submission to matching engine
        - Individual order failures during engine processing don't reject entire batch

    Usage Example:
        >>> order_item = BatchOrderItem(
        ...     ordertype="limit",
        ...     type="buy",
        ...     volume=1.5,
        ...     price="50000"
        ... )
    """

    userref: int | None = Field(
        default=None,
        description="User reference id. Mutually exclusive with cl_ord_id parameter.",
    )
    cl_ord_id: str | None = Field(
        default=None,
        description="Alphanumeric client order identifier. Mutually exclusive with userref parameter.",
    )
    ordertype: ORDER_TYPE = Field(..., description="The execution model of the order.")
    type: ORDER_DIRECTION = Field(..., description="Order direction (buy/sell).")
    volume: str | float | int = Field(
        ...,
        description="Order quantity in terms of the base asset.",
    )
    displayvol: str | float | int | None = Field(
        default=None,
        description="For iceberg orders only, visible quantity in the book.",
    )
    price: str | None = Field(
        default=None,
        description="Limit price for limit/iceberg orders; trigger price for stop-loss/take-profit orders.",
    )
    price2: str | None = Field(
        default=None,
        description="Limit price for stop-loss-limit and take-profit-limit orders.",
    )
    trigger: TRIGGER_TYPE | None = Field(
        default=None,
        description="Price signal used to trigger stop-loss and take-profit orders.",
    )
    leverage: str | int | None = Field(None, description="Amount of desired leverage.")
    reduce_only: bool = Field(
        default=False,
        description="If True, order will only reduce a currently open position.",
    )
    stptype: STP_TYPE | None = Field(
        default=None,
        description="Self Trade Prevention (STP) behavior.",
    )
    oflags: str | list[str] | set[str] | None = Field(
        default=None,
        description="Comma delimited list of order flags: 'post', 'fcib', 'fciq', 'viqc'.",
    )
    timeinforce: TIME_IN_FORCE | None = Field(
        default="GTC",
        description="Time-in-force of the order.",
    )
    starttm: str | None = Field(
        default="0",
        description="Scheduled start time.",
    )
    expiretm: str | None = Field(
        default="0",
        description="Expiry time on GTD orders.",
    )

    @field_validator("ordertype", mode="before")
    @classmethod
    def lowercase_order(cls, value: str) -> str:
        return validators.validate_ordertype(value)

    @field_validator("volume", mode="before")
    @classmethod
    def string_volume(cls, value: str | float | int) -> str:
        return validators.validate_volume(value)

    @field_validator("displayvol", mode="before")
    @classmethod
    def floor_display_volume(cls, value: str | float | int | None, info) -> str | None:
        if value is None:
            return None
        order_volume = float(info.data.get("volume"))
        return validators.validate_display_volume(value, order_volume)

    @field_validator("leverage", mode="before")
    @classmethod
    def string_leverage(cls, value: str | int | None) -> str | None:
        return validators.validate_leverage(value)

    @field_validator("oflags", mode="before")
    @classmethod
    def concat_order_flags(cls, value: str | list[str] | set[str] | None) -> str | None:
        return validators.validate_order_flags(value)

    @field_validator("timeinforce", mode="before")
    @classmethod
    def capitalize_time_in_force(cls, value: str) -> str:
        return validators.validate_time_in_force(value)

    @model_validator(mode="after")
    def validate_field_dependencies(self) -> "BatchOrderItem":
        """Validate field dependencies for different order types."""
        if (
            self.ordertype in ["iceberg", "limit", "stop-loss", "take-profit", "trailing-stop"]
            and self.price is None
        ):
            raise ValueError(f"{self.ordertype} orders require 'price' field")
        if self.ordertype in ["stop-loss-limit", "take-profit-limit", "trailing-stop-limit"]:
            if self.price is None or self.price2 is None:
                raise ValueError(
                    f"{self.ordertype} orders require both 'price' and 'price2' fields"
                )
        if self.timeinforce == "GTD" and (self.expiretm is None or self.expiretm == "0"):
            raise ValueError("GTD (Good-Til-Date) orders require 'expiretm' field")
        if self.userref is not None and self.cl_ord_id is not None:
            raise ValueError("'userref' and 'cl_ord_id' are mutually exclusive")
        return self


class AddOrderBatchRequest(BaseRequestSchema):
    """Schema for Kraken AddOrderBatch API request.

    This schema validates and prepares batch order data for submission to Kraken's
    AddOrderBatch API endpoint. Batch orders allow submitting 2-15 orders in a
    single request for the same trading pair.

    Important Notes:
        - Minimum 2 orders, maximum 15 orders per batch
        - All orders must be for the same trading pair
        - Validation is performed on the whole batch prior to submission
        - If an order fails validation, the whole batch will be rejected
        - On submission to engine, individual order failures don't reject entire batch
        - The 'nonce' parameter is automatically generated by the REST client
        - The 'deadline' parameter is NOT auto-generated during instantiation
        - Use to_api_dict() to serialize for API submission

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        Time-sensitive fields (nonce, deadline) are handled by the REST client
        at the last possible moment before request signing.

    Usage Examples:
        Batch of limit orders:
        >>> batch = AddOrderBatchRequest(
        ...     orders=[
        ...         BatchOrderItem(ordertype="limit", type="buy", volume=1.0, price="50000"),
        ...         BatchOrderItem(ordertype="limit", type="buy", volume=0.5, price="49000"),
        ...     ],
        ...     pair="XBTUSD"
        ... )
        >>> data = batch.to_api_dict()
        >>> response = client.request("AddOrderBatch", data=data)

        Mixed order types:
        >>> batch = AddOrderBatchRequest(
        ...     orders=[
        ...         BatchOrderItem(ordertype="market", type="buy", volume=1.0),
        ...         BatchOrderItem(ordertype="limit", type="sell", volume=1.0, price="55000"),
        ...         BatchOrderItem(ordertype="stop-loss", type="sell", volume=1.0, price="45000"),
        ...     ],
        ...     pair="XBTUSD"
        ... )

        Validation only:
        >>> batch = AddOrderBatchRequest(
        ...     orders=[...],
        ...     pair="XBTUSD",
        ...     only_validate=True
        ... )
    """

    orders: list[BatchOrderItem] = Field(
        ...,
        description="Array of orders (minimum 2, maximum 15).",
    )
    pair: str = Field(
        ..., description="Asset pair id or altname (all orders must be for this pair)."
    )
    asset_class: str | None = Field(
        None, description="Required to be set as 'tokenized_asset' for non-crypto pairs (xstocks)."
    )
    deadline: str | None = Field(
        default=None,
        description="RFC3339 timestamp after which the matching engine should reject the batch request.",
    )
    only_validate: bool = Field(
        default=False,
        description="If True, validates batch inputs without placing orders.",
        validation_alias=AliasChoices("only_validate", "validate"),  # Accept both names
        serialization_alias="validate",  # Send as 'validate' to API
    )

    @field_validator("orders", mode="after")
    @classmethod
    def validate_batch_size(cls, value: list[BatchOrderItem]) -> list[BatchOrderItem]:
        """Validate batch contains 2-15 orders."""
        if len(value) < 2:
            raise ValueError(f"Batch must contain at least 2 orders, got {len(value)}")
        if len(value) > 15:
            raise ValueError(f"Batch must contain at most 15 orders, got {len(value)}")
        return value

    @field_validator("deadline", mode="after")
    @classmethod
    def validate_deadline(cls, value: str | None) -> str | None:
        """Validate deadline format and timezone information."""
        return validators.validate_deadline(value)


class BatchOrderResult(BaseSchema):
    """Result for an individual order within an AddOrderBatch response.

    Represents the outcome of a single order in a batch submission.
    """

    txid: str | None = Field(
        default=None,
        description="Transaction ID for order (if order was added successfully).",
    )
    descr: dict | None = Field(
        default=None,
        description="Order description info (if order was added successfully).",
    )
    error: str | None = Field(
        default=None,
        description="Error description from individual order processing (if order failed).",
    )

    @property
    def is_success(self) -> bool:
        """Check if the individual order was successful."""
        return self.txid is not None and self.error is None


class AddOrderBatchSuccess(BaseSchema):
    """Successful AddOrderBatch response from Kraken API.

    Contains results for each order in the batch. The order of results matches
    the order of the request.
    """

    orders: list[BatchOrderResult] = Field(
        ...,
        description="Results for each order in the batch (order matches request order).",
    )


class AddOrderBatchResponse(BaseResponseWrapper[AddOrderBatchSuccess]):
    """Combined response wrapper for AddOrderBatch API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.

    Note: Even in success cases, individual orders may have errors. Check
    each BatchOrderResult for individual order outcomes.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "AddOrderBatchResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            AddOrderBatchResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")

        orders_data = result.get("orders", [])
        batch_results = []
        for order_data in orders_data:
            batch_result = BatchOrderResult(
                txid=order_data.get("txid"),
                descr=order_data.get("descr"),
                error=order_data.get("error"),
            )
            batch_results.append(batch_result)

        success_data = AddOrderBatchSuccess(orders=batch_results)
        return cls(success=success_data)


class CancelOrderBatchItem(OrderIdentifierMixin):
    """Schema for individual order identifier in a CancelOrderBatch request.

    Represents a single order to cancel by either transaction ID (txid),
    user reference (userref), or client order ID (cl_ord_id).
    """

    pass


class CancelOrderBatchRequest(BaseRequestSchema):
    """Schema for Kraken CancelOrderBatch API request.

    This schema validates and prepares batch cancellation data for submission to
    Kraken's CancelOrderBatch API endpoint. Allows cancelling up to 50 orders in
    a single request.

    Important Notes:
        - Maximum 50 unique IDs/references per batch
        - Must provide either 'orders' or 'cl_ord_ids' (or both)
        - The 'nonce' parameter is automatically generated by the REST client
        - Use to_api_dict() to serialize for API submission

    Thread Safety:
        This schema is thread-safe for instantiation and validation.
        The nonce field is handled by the REST client at the last possible
        moment before request signing.

    Usage Examples:
        Cancel by transaction IDs:
        >>> batch = CancelOrderBatchRequest(
        ...     orders=[
        ...         CancelOrderBatchItem(txid="OUF4EM-FRGI2-MQMWZD"),
        ...         CancelOrderBatchItem(txid="ABC123-DEF456-GHI789"),
        ...     ]
        ... )
        >>> response = client.request("CancelOrderBatch", data=batch.to_api_dict())

        Cancel by user references:
        >>> batch = CancelOrderBatchRequest(
        ...     orders=[
        ...         CancelOrderBatchItem(txid=12345),
        ...         CancelOrderBatchItem(txid=67890),
        ...     ]
        ... )

        Cancel by client order IDs:
        >>> batch = CancelOrderBatchRequest(
        ...     cl_ord_ids=["my-order-1", "my-order-2", "my-order-3"]
        ... )

        Mixed cancellation:
        >>> batch = CancelOrderBatchRequest(
        ...     orders=[CancelOrderBatchItem(txid="ABC-123")],
        ...     cl_ord_ids=["client-order-1"]
        ... )
    """

    orders: list[CancelOrderBatchItem] | None = Field(
        default=None,
        description="Array of order identifiers to cancel (up to 50 total).",
    )
    cl_ord_ids: list[str] | None = Field(
        default=None,
        description="Array of client order IDs to cancel (up to 50 total).",
    )

    @model_validator(mode="after")
    def validate_batch_constraints(self) -> "CancelOrderBatchRequest":
        """Validate batch size and that at least one identifier type is provided."""
        if self.orders is None and self.cl_ord_ids is None:
            raise ValueError("Either 'orders' or 'cl_ord_ids' must be provided")

        # Count total items
        total_items = 0
        if self.orders is not None:
            total_items += len(self.orders)
        if self.cl_ord_ids is not None:
            total_items += len(self.cl_ord_ids)

        if total_items > 50:
            raise ValueError(f"Batch must contain at most 50 total items, got {total_items}")

        return self


class CancelOrderBatchSuccess(BaseSchema):
    """Successful CancelOrderBatch response from Kraken API.

    Contains the number of orders cancelled.
    """

    count: int = Field(
        ...,
        description="Number of orders cancelled.",
    )


class CancelOrderBatchResponse(BaseResponseWrapper[CancelOrderBatchSuccess]):
    """Combined response wrapper for CancelOrderBatch API calls.

    This wrapper handles both success and error cases from the Kraken API.
    Use the `is_success` property to determine the outcome and access the
    appropriate `success` or `error` attribute.
    """

    @classmethod
    def from_response(cls, response: dict | str) -> "CancelOrderBatchResponse":
        """Parse a Kraken API response into the appropriate response model.

        Args:
            response: Either a JSON string or dict containing the API response

        Returns:
            CancelOrderBatchResponse with either success or error data populated

        Raises:
            ValueError: If the response format is invalid
        """
        if isinstance(response, str):
            response = json.loads(response)
        errors = response.get("error", [])
        if errors:
            error_data = ResponseErrorSchema(error=errors)
            return cls(failure=error_data)

        result = response.get("result")
        if not result:
            raise ValueError("Response missing 'result' field")
        success_data = CancelOrderBatchSuccess(count=result["count"])
        return cls(success=success_data)
